using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HatemogluApp.Models;
using Rg.Plugins.Popup.Extensions;
using Rg.Plugins.Popup.Services;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace HatemogluApp.Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Urunler : ContentPage
    {
        private static List<Urun> gelenyeniListe;
        private static List<Urun> staticList;
        static string baslik;
        internal static List<Urun> StaticList { get => staticList; set => staticList = value; }
        internal static List<Urun> GelenyeniListe { get => gelenyeniListe; set => gelenyeniListe = value; }

        public Urunler()
        {
            InitializeComponent();
        }
        public Urunler(object list)
        {
            InitializeComponent();
            List<Urun> a = list as List<Urun>;
            liste.ItemsSource = a;
            title.Text = baslik;
        }
        private async void Button_Clicked_logo(object sender, EventArgs e)
        {
            await Shell.Current.GoToAsync($"//anasayfa");
        }
        private async void Button_Clicked_sepetim(object sender, EventArgs e)
        {
            await Shell.Current.GoToAsync($"//sepetim");
        }
        public Urunler(string g_urun)
        {
            InitializeComponent();
            
            title.Text = g_urun;
            baslik = title.Text;
            
            if (g_urun == "Gömlekler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-beyaz-gomlek-20d190000111-001-beyaz-gomlek-hatemoglu-43586-94-K.jpg", Baslik = "Slim Fit Beyaz Gömlek", Eskifiyat = "179.99₺", Fiyat = "99.99", Indirim = "%44", Ozellikler = "Kumaş: %55 Pamuk %45 Polyester\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni :  M\nUzun Kol\nKlasik Yaka Düz Renk\nYerli Üretim\nNormal Manşet\nKolay Ütülenir\nCepsiz\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-yaka-dugmeli-beyaz-oxford-gomlek-beyaz-gomlek-hatemoglu-54844-10-K.jpg", Baslik = "Slim Fit Yaka Düğmeli Beyaz Oxford Gömlek", Eskifiyat = "229.00₺", Fiyat = "89.99", Indirim = "%61", Ozellikler = "Kumaş: %60 Pamuk %40 Polyester\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni :  M\nUzun Kol\nDüğmeli Yaka\nDüz Renk\nYerli Üretim\nNormal Manşet\nOxford Kumaş\nCepsiz\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-slim-fit-lila-gomlek-4771-armurlu-gomlek-hatemoglu-38600-47-K.jpg", Baslik = "Desenli Slim Fit Lila Gömlek", Eskifiyat = "129.00₺", Fiyat = "49.99", Indirim = "%61", Ozellikler = "HATEMOĞLU Desenli %60 PAMUK %40 POLYESTER Slim Fit Gömlek" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/cizgili-slim-fit-lacivert-gomlek-4628-mavi-gomlek-hatem-sayki-38068-46-K.jpg", Baslik = "Çizgili Slim Fit Lacivert Gömlek", Eskifiyat = "189.9₺", Fiyat = "49.99", Indirim = "%74", Ozellikler = "HATEM SAYKI Çizgili %100 Pamuk Slim Fit Gömlek" };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-baskili-kahverengi-gomlek-5176-baskili-gomlek-html-43867-51-K.jpg", Baslik = "Slim Fit Baskılı Kahverengi Gömlek", Eskifiyat = "249.0₺", Fiyat = "59.99", Indirim = "%76", Ozellikler = "Kumaş: %50 Polyester %50 Pamuk\nKalıp: Slim Fit\nGörseldeki Ürün Bedeni: M\nUzun Kol\nKlasik Yaka\nBaskılı\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                Urun urun6 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-d-desenli-slim-fit-gomlek-10388-slim-fit-gomlek-hatem-sayki-47957-10-K.jpg", Baslik = "Spor Lacivert Gömlek", Eskifiyat = "329.00₺", Fiyat = "169.90", Indirim = "%48", Ozellikler = "HATEM SAYKI Desenli %100 Pamuk Slim Fit Gömlek" };
                Urun urun7 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/gri-b-baskili-slim-fit-gomlek-10448-baskili-gomlek-html-47636-10-K.jpg", Baslik = "Baskılı Gri Spor Gömlek", Eskifiyat = "209.00₺", Fiyat = "169.90", Indirim = "%41", Ozellikler = "HTML Baskılı %100 Pamuk Slim Fit Gömlek" };
                Urun urun8 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/sari-c-1-casual-cizgili-slim-fit-gomlek-beyaz-gomlek-html-47707-10-K.jpg", Baslik = "Çizgili Beyaz Spor Gömlek", Eskifiyat = "219.00₺", Fiyat = "149.90", Indirim = "%32", Ozellikler = "HTML Casual - Çizgili %60 PAMUK %40 POLYESTER Slim Fit Gömlek" };
                Urun urun9 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-mavi-gomlek-20d190000111-010-mavi-gomlek-hatemoglu-43984-94-K.jpg", Baslik = "Spor Mavi Gömlek", Eskifiyat = "179.00₺", Fiyat = "69.90", Indirim = "%61", Ozellikler = "Kumaş: %55 Pamuk %45 Polyester\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni :  M\nUzun Kol\nKlasik Yaka\nDüz Renk\nYerli Üretim\nNormal Manşet\nKolay Ütülenir\nCepsiz\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun10 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/yesil-b-baskili-slim-fit-gomlek-10453-beyaz-gomlek-hatem-sayki-47653-10-K.jpg", Baslik = "Desenli Beyaz Spor Gömlek", Eskifiyat = "209.00₺", Fiyat = "169.90", Indirim = "%41", Ozellikler = "HATEM SAYKI Baskılı %100 Pamuk Slim Fit Gömlek" };

                Urun urun11 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/a-mavi-d-desenli-klasik-gomlek-mavi-gomlek-hatemoglu-38003-47-K.jpg", Baslik = "Desenli Klasik Mavi Gömlek", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "HATEMOĞLU Desenli %100 Pamuk Klasik Gömlek" };
                Urun urun12 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/a-mavi-d-desenli-regular-gomlek-4716-mavi-gomlek-hatemoglu-38018-47-K.jpg", Baslik = "Desenli Regular Mavi Gömlek", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "HATEMOĞLU Desenli %100 Pamuk Regular Gömlek" };
                Urun urun13 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-klasik-gri-gomlek-armurlu-gomlek-hatemoglu-39561-46-K.jpg", Baslik = "Desenli Klasik Gri Gömlek", Eskifiyat = "149.00₺", Fiyat = "49.99", Indirim = "%66", Ozellikler = "HATEMOĞLU Desenli %100 Pamuk Klasik Gömlek" };
                Urun urun14 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/kareli-klasik-lacivert-gomlek-5326-mavi-gomlek-hatemoglu-35223-53-K.jpg", Baslik = "Kareli Klasik Lacivert Gömlek", Eskifiyat = "179.00₺", Fiyat = "69.99", Indirim = "%61", Ozellikler = "Kumaş: %60 Pamuk %40 Polyester\nKalıp: Klasik Fit\nGörseldeki Ürün Bedeni: M\nKısa kollu\nKlasik yaka\nKareli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun15 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/kareli-klasik-haki-gomlek-5325-klasik-gomlek-hatemoglu-35230-53-K.jpg", Baslik = "Kareli Klasik Haki Gömlek", Eskifiyat = "179.00₺", Fiyat = "69.99", Indirim = "%61", Ozellikler = "Kumaş: %60 Pamuk %40 Polyester\nKalıp: Klasik Fit\nGörseldeki Ürün Bedeni: M\nKısa kollu\nKlasik yaka\nKareli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };


                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5, urun6, urun7, urun8, urun9, urun10, urun11, urun12, urun13, urun14, urun15 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Slim Fit Gömlekler")
            {
                Urun urun1 = new Urun { Tur= g_urun, Resim = "https://www.hatemoglu.com/slim-fit-beyaz-gomlek-20d190000111-001-beyaz-gomlek-hatemoglu-43586-94-K.jpg", Baslik = "Slim Fit Beyaz Gömlek", Eskifiyat = "179.99₺", Fiyat = "99.99", Indirim = "%44", Ozellikler = "Kumaş: %55 Pamuk %45 Polyester\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni :  M\nUzun Kol\nKlasik Yaka Düz Renk\nYerli Üretim\nNormal Manşet\nKolay Ütülenir\nCepsiz\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-yaka-dugmeli-beyaz-oxford-gomlek-beyaz-gomlek-hatemoglu-54844-10-K.jpg", Baslik = "Slim Fit Yaka Düğmeli Beyaz Oxford Gömlek", Eskifiyat = "229.00₺", Fiyat = "89.99", Indirim = "%61", Ozellikler = "Kumaş: %60 Pamuk %40 Polyester\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni :  M\nUzun Kol\nDüğmeli Yaka\nDüz Renk\nYerli Üretim\nNormal Manşet\nOxford Kumaş\nCepsiz\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-slim-fit-lila-gomlek-4771-armurlu-gomlek-hatemoglu-38600-47-K.jpg", Baslik = "Desenli Slim Fit Lila Gömlek", Eskifiyat = "129.00₺", Fiyat = "49.99", Indirim = "%61", Ozellikler = "HATEMOĞLU Desenli %60 PAMUK %40 POLYESTER Slim Fit Gömlek" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/cizgili-slim-fit-lacivert-gomlek-4628-mavi-gomlek-hatem-sayki-38068-46-K.jpg", Baslik = "Çizgili Slim Fit Lacivert Gömlek", Eskifiyat = "189.9₺", Fiyat = "49.99", Indirim = "%74", Ozellikler = "HATEM SAYKI Çizgili %100 Pamuk Slim Fit Gömlek" };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-baskili-kahverengi-gomlek-5176-baskili-gomlek-html-43867-51-K.jpg", Baslik = "Slim Fit Baskılı Kahverengi Gömlek", Eskifiyat = "249.0₺", Fiyat = "59.99", Indirim = "%76", Ozellikler = "Kumaş: %50 Polyester %50 Pamuk\nKalıp: Slim Fit\nGörseldeki Ürün Bedeni: M\nUzun Kol\nKlasik Yaka\nBaskılı\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
               
                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5};
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Spor Gömlekler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-d-desenli-slim-fit-gomlek-10388-slim-fit-gomlek-hatem-sayki-47957-10-K.jpg", Baslik = "Spor Lacivert Gömlek", Eskifiyat = "329.00₺", Fiyat = "169.90", Indirim = "%48", Ozellikler = "HATEM SAYKI Desenli %100 Pamuk Slim Fit Gömlek" };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/gri-b-baskili-slim-fit-gomlek-10448-baskili-gomlek-html-47636-10-K.jpg", Baslik = "Baskılı Gri Spor Gömlek", Eskifiyat = "209.00₺", Fiyat = "169.90", Indirim = "%41", Ozellikler = "HTML Baskılı %100 Pamuk Slim Fit Gömlek" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/sari-c-1-casual-cizgili-slim-fit-gomlek-beyaz-gomlek-html-47707-10-K.jpg", Baslik = "Çizgili Beyaz Spor Gömlek", Eskifiyat = "219.00₺", Fiyat = "149.90", Indirim = "%32", Ozellikler = "HTML Casual - Çizgili %60 PAMUK %40 POLYESTER Slim Fit Gömlek" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-mavi-gomlek-20d190000111-010-mavi-gomlek-hatemoglu-43984-94-K.jpg", Baslik = "Spor Mavi Gömlek", Eskifiyat = "179.00₺", Fiyat = "69.90", Indirim = "%61", Ozellikler = "Kumaş: %55 Pamuk %45 Polyester\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni :  M\nUzun Kol\nKlasik Yaka\nDüz Renk\nYerli Üretim\nNormal Manşet\nKolay Ütülenir\nCepsiz\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/yesil-b-baskili-slim-fit-gomlek-10453-beyaz-gomlek-hatem-sayki-47653-10-K.jpg", Baslik = "Desenli Beyaz Spor Gömlek", Eskifiyat = "209.00₺", Fiyat = "169.90", Indirim = "%41", Ozellikler = "HATEM SAYKI Baskılı %100 Pamuk Slim Fit Gömlek" };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Klasik Gömlekler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/a-mavi-d-desenli-klasik-gomlek-mavi-gomlek-hatemoglu-38003-47-K.jpg", Baslik = "Desenli Klasik Mavi Gömlek", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "HATEMOĞLU Desenli %100 Pamuk Klasik Gömlek" };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/a-mavi-d-desenli-regular-gomlek-4716-mavi-gomlek-hatemoglu-38018-47-K.jpg", Baslik = "Desenli Regular Mavi Gömlek", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "HATEMOĞLU Desenli %100 Pamuk Regular Gömlek" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-klasik-gri-gomlek-armurlu-gomlek-hatemoglu-39561-46-K.jpg", Baslik = "Desenli Klasik Gri Gömlek", Eskifiyat = "149.00₺", Fiyat = "49.99", Indirim = "%66", Ozellikler = "HATEMOĞLU Desenli %100 Pamuk Klasik Gömlek" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/kareli-klasik-lacivert-gomlek-5326-mavi-gomlek-hatemoglu-35223-53-K.jpg", Baslik = "Kareli Klasik Lacivert Gömlek", Eskifiyat = "179.00₺", Fiyat = "69.99", Indirim = "%61", Ozellikler = "Kumaş: %60 Pamuk %40 Polyester\nKalıp: Klasik Fit\nGörseldeki Ürün Bedeni: M\nKısa kollu\nKlasik yaka\nKareli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/kareli-klasik-haki-gomlek-5325-klasik-gomlek-hatemoglu-35230-53-K.jpg", Baslik = "Kareli Klasik Haki Gömlek", Eskifiyat = "179.00₺", Fiyat = "69.99", Indirim = "%61", Ozellikler = "Kumaş: %60 Pamuk %40 Polyester\nKalıp: Klasik Fit\nGörseldeki Ürün Bedeni: M\nKısa kollu\nKlasik yaka\nKareli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Ceketler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/antrasit-slim-fit-desenli-ceket-spor-ceket-html-47771-10-K.jpg", Baslik = "Slim Fit Gri Desenli Ceket", Eskifiyat = "895.00₺", Fiyat = "299.90", Indirim = "%66", Ozellikler = "Kumaş: %78 Polyester %19 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nMono Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nTorba Cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-slim-fit-spor-ceket-spor-ceket-hatemoglu-47799-10-K.jpg", Baslik = "Slim Fit Lacivert Ceket", Eskifiyat = "895.00₺", Fiyat = "299.90", Indirim = "%66", Ozellikler = "Kumaş: %78 Polyester %19 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nMono Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nTorba Cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-d-desenli-slim-fit-ceket-10721-slim-fit-ceket-hatemoglu-53332-10-K.jpg", Baslik = "Desenli Slim Lacivert Fit Ceket", Eskifiyat = "835.00₺", Fiyat = "599.90", Indirim = "%28", Ozellikler = "Kumaş: %80 Polyester %17 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nYakada Aksesuar\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/a-mavi-d-desenli-slim-fit-ceket-10437-spor-ceket-hatemoglu-47935-10-K.jpg", Baslik = "Slim Fit Açık Mavi Ceket", Eskifiyat = "849.00₺", Fiyat = "499.90", Indirim = "%41", Ozellikler = "Kumaş: %49 Polyester %48 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/bej-desenli-slim-fit-ceket-9763-klasik-ceket-html-44801-97-K.jpg", Baslik = "Slim Bej Fit Ceket", Eskifiyat = "695.00₺", Fiyat = "399.90", Indirim = "%42", Ozellikler = "Kumaş: %82 Polyester %15 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 97 cm, Bel: 81 cm Kilo: 81kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                Urun urun6 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/kiremit-slim-fit-desenli-ceket-slim-fit-ceket-hatemoglu-53907-10-K.jpg", Baslik = "Desenli Kiremit Spor Ceket", Eskifiyat = "895.00₺", Fiyat = "299.90", Indirim = "%66", Ozellikler = "Kumaş: %76 Polyester %19 Viskon %5 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nMono Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nYakada Aksesuar\nTorba Cep\nEsnek Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun7 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/haki-slim-fit-desenli-ceket-slim-fit-ceket-hatemoglu-47806-10-K.jpg", Baslik = "Desenli Haki Spor Ceket", Eskifiyat = "895.00₺", Fiyat = "299.90", Indirim = "%66", Ozellikler = "Kumaş: %76 Polyester %19 Viskon %5 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nMono Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nYakada Aksesuar\nTorba Cep\nEsnek Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun8 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-desenli-slim-fit-ceket-8995-slim-fit-ceket-hatem-sayki-44823-89-K.jpg", Baslik = "Desenli Lacivert Blazer Spor Ceket", Eskifiyat = "985.00₺", Fiyat = "549.90", Indirim = "%44", Ozellikler = "Kumaş: %45 Yün %36 Pamuk %17 Polyamid %2 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 97 cm, Bel: 81 cm Kilo: 81kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nYakada Aksesuar\nYünlü Kumaş\nKapaklı cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun9 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/cizgili-slim-fit-pembe-yun-ceket-3765-slim-fit-ceket-hatem-sayki-44548-37-K.jpg", Baslik = "Çizgili Pembe Spor Ceket", Eskifiyat = "835.0₺", Fiyat = "249.90", Indirim = "%70", Ozellikler = "Kumaş: %100 Pamuk\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nSivri Yaka\nÇizgili\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nYakada Aksesuar\n% 100 Pamuk\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun10 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/bej-d-desenli-slim-fit-ceket-20648-slim-fit-ceket-html-47449-10-K.jpg", Baslik = "Spor Bej Ceket", Eskifiyat = "735.0₺", Fiyat = "249.90", Indirim = "%66", Ozellikler = "Kumaş: %45 Pamuk %38 Likra %9 Polyester %8 Viskon\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                Urun urun11 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/kahverengi-slim-fit-ekoseli-ceket-spor-ceket-hatemoglu-47819-10-K.jpg", Baslik = "Ekoseli Kahverengi Klasik Ceket", Eskifiyat = "835.00₺", Fiyat = "299.90", Indirim = "%64", Ozellikler = "Kumaş: %71 Polyester %25 Viskon %4 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nKlasik Yaka\nKareli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nYakada Aksesuar\nTorba Cep\nEsnek Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun12 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/yesil-slim-fit-ekoseli-ceket-spor-ceket-hatemoglu-47826-10-K.jpg", Baslik = "Ekoseli Yeşil Klasik Ceket", Eskifiyat = "835.00₺", Fiyat = "299.90", Indirim = "%64", Ozellikler = "Kumaş: %71 Polyester %25 Viskon %4 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nKlasik Yaka\nKareli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nYakada Aksesuar\nTorba Cep\nEsnek Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun13 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/yesil-slim-fit-desenli-ceket-spor-ceket-html-47792-10-K.jpg", Baslik = "Desenli Yeşil Klasik Ceket", Eskifiyat = "835.00₺", Fiyat = "299.90", Indirim = "%64", Ozellikler = "Kumaş: %79 Polyester %19 Viskon %2 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nKırlangıç Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nTorba Cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun14 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/bordo-k-kareli-slim-fit-ceket-10329-spor-ceket-hatemoglu-53192-10-K.jpg", Baslik = "Ekoseli Kahverengi Slim Fit Ceket", Eskifiyat = "895.00₺", Fiyat = "599.90", Indirim = "%33", Ozellikler = "Kumaş: %82 Polyester %18 Viskon\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKareli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nYakada Aksesuar\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun15 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/mavi-d-desenli-slim-fit-ceket-10436-spor-ceket-hatemoglu-47929-10-K.jpg", Baslik = "Klasik Ceket", Eskifiyat = "849.00₺", Fiyat = "499.90", Indirim = "%41", Ozellikler = "Kumaş: %79 Polyester %19 Viskon %2 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nKırlangıç Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nTorba Cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5, urun6, urun7, urun8, urun9, urun10, urun11, urun12, urun13, urun14, urun15 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Slim Fit Ceketler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/antrasit-slim-fit-desenli-ceket-spor-ceket-html-47771-10-K.jpg", Baslik = "Slim Fit Gri Desenli Ceket", Eskifiyat = "895.00₺", Fiyat = "299.90", Indirim = "%66", Ozellikler = "Kumaş: %78 Polyester %19 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nMono Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nTorba Cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-slim-fit-spor-ceket-spor-ceket-hatemoglu-47799-10-K.jpg", Baslik = "Slim Fit Lacivert Ceket", Eskifiyat = "895.00₺", Fiyat = "299.90", Indirim = "%66", Ozellikler = "Kumaş: %78 Polyester %19 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nMono Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nTorba Cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-d-desenli-slim-fit-ceket-10721-slim-fit-ceket-hatemoglu-53332-10-K.jpg", Baslik = "Desenli Slim Lacivert Fit Ceket", Eskifiyat = "835.00₺", Fiyat = "599.90", Indirim = "%28", Ozellikler = "Kumaş: %80 Polyester %17 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nYakada Aksesuar\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/a-mavi-d-desenli-slim-fit-ceket-10437-spor-ceket-hatemoglu-47935-10-K.jpg", Baslik = "Slim Fit Açık Mavi Ceket", Eskifiyat = "849.00₺", Fiyat = "499.90", Indirim = "%41", Ozellikler = "Kumaş: %49 Polyester %48 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/bej-desenli-slim-fit-ceket-9763-klasik-ceket-html-44801-97-K.jpg", Baslik = "Slim Bej Fit Ceket", Eskifiyat = "695.00₺", Fiyat = "399.90", Indirim = "%42", Ozellikler = "Kumaş: %82 Polyester %15 Viskon %3 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 97 cm, Bel: 81 cm Kilo: 81kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Spor Ceketler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/kiremit-slim-fit-desenli-ceket-slim-fit-ceket-hatemoglu-53907-10-K.jpg", Baslik = "Desenli Kiremit Spor Ceket", Eskifiyat = "895.00₺", Fiyat = "299.90", Indirim = "%66", Ozellikler = "Kumaş: %76 Polyester %19 Viskon %5 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nMono Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nYakada Aksesuar\nTorba Cep\nEsnek Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/haki-slim-fit-desenli-ceket-slim-fit-ceket-hatemoglu-47806-10-K.jpg", Baslik = "Desenli Haki Spor Ceket", Eskifiyat = "895.00₺", Fiyat = "299.90", Indirim = "%66", Ozellikler = "Kumaş: %76 Polyester %19 Viskon %5 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nMono Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nYakada Aksesuar\nTorba Cep\nEsnek Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-desenli-slim-fit-ceket-8995-slim-fit-ceket-hatem-sayki-44823-89-K.jpg", Baslik = "Desenli Lacivert Blazer Spor Ceket", Eskifiyat = "985.00₺", Fiyat = "549.90", Indirim = "%44", Ozellikler = "Kumaş: %45 Yün %36 Pamuk %17 Polyamid %2 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 97 cm, Bel: 81 cm Kilo: 81kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nYakada Aksesuar\nYünlü Kumaş\nKapaklı cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/cizgili-slim-fit-pembe-yun-ceket-3765-slim-fit-ceket-hatem-sayki-44548-37-K.jpg", Baslik = "Çizgili Pembe Spor Ceket", Eskifiyat = "835.0₺", Fiyat = "249.90", Indirim = "%70", Ozellikler = "Kumaş: %100 Pamuk\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nSivri Yaka\nÇizgili\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nYakada Aksesuar\n% 100 Pamuk\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/bej-d-desenli-slim-fit-ceket-20648-slim-fit-ceket-html-47449-10-K.jpg", Baslik = "Spor Bej Ceket", Eskifiyat = "735.0₺", Fiyat = "249.90", Indirim = "%66", Ozellikler = "Kumaş: %45 Pamuk %38 Likra %9 Polyester %8 Viskon\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKendinden desenli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Klasik Ceketler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/kahverengi-slim-fit-ekoseli-ceket-spor-ceket-hatemoglu-47819-10-K.jpg", Baslik = "Ekoseli Kahverengi Klasik Ceket", Eskifiyat = "835.00₺", Fiyat = "299.90", Indirim = "%64", Ozellikler = "Kumaş: %71 Polyester %25 Viskon %4 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nKlasik Yaka\nKareli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nYakada Aksesuar\nTorba Cep\nEsnek Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/yesil-slim-fit-ekoseli-ceket-spor-ceket-hatemoglu-47826-10-K.jpg", Baslik = "Ekoseli Yeşil Klasik Ceket", Eskifiyat = "835.00₺", Fiyat = "299.90", Indirim = "%64", Ozellikler = "Kumaş: %71 Polyester %25 Viskon %4 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nKlasik Yaka\nKareli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nYakada Aksesuar\nTorba Cep\nEsnek Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/yesil-slim-fit-desenli-ceket-spor-ceket-html-47792-10-K.jpg", Baslik = "Desenli Yeşil Klasik Ceket", Eskifiyat = "835.00₺", Fiyat = "299.90", Indirim = "%64", Ozellikler = "Kumaş: %79 Polyester %19 Viskon %2 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nKırlangıç Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nTorba Cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/bordo-k-kareli-slim-fit-ceket-10329-spor-ceket-hatemoglu-53192-10-K.jpg", Baslik = "Ekoseli Kahverengi Slim Fit Ceket", Eskifiyat = "895.00₺", Fiyat = "599.90", Indirim = "%33", Ozellikler = "Kumaş: %82 Polyester %18 Viskon\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun kol\nMono Yaka\nKareli\nYerli Üretim\nTam Astar\nÇift Yırtmaç\nYakada Aksesuar\nTorba cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/mavi-d-desenli-slim-fit-ceket-10436-spor-ceket-hatemoglu-47929-10-K.jpg", Baslik = "Klasik Ceket", Eskifiyat = "849.00₺", Fiyat = "499.90", Indirim = "%41", Ozellikler = "Kumaş: %79 Polyester %19 Viskon %2 Elastan\nKalıp: Slim Fit\nDrop: 6 Drop\nModel Ölçüsü: Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 50\nUzun Kol\nKırlangıç Yaka\nKendinden Desenli\nYerli Üretim\nMartı Astar\nÇift Yırtmaç\nYumuşak Omuz\nTorba Cep\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Tişörtler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-baskili-regular-t-shirt-22512-online-ozel-hatemoglu-55095-22-K.jpg", Baslik = "Bisiklet Yaka Siyah Basic Tişört", Eskifiyat = "119.00₺", Fiyat = "69.99", Indirim = "%41", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-baskili-regular-t-shirt-22513-online-ozel-hatemoglu-55097-22-K.jpg", Baslik = "Bisiklet Yaka Lacivert Basic Tişört", Eskifiyat = "119.00₺", Fiyat = "69.99", Indirim = "%41", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/beyaz-baskili-regular-t-shirt-22511-online-ozel-hatemoglu-55093-22-K.jpg", Baslik = "Bisiklet Yaka Beyaz Basic Tişört", Eskifiyat = "119.00₺", Fiyat = "69.99", Indirim = "%41", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/haki-baskili-regular-t-shirt-online-ozel-hatemoglu-55099-22-K.jpg", Baslik = "Bisiklet Yaka Haki Basic Tişört", Eskifiyat = "119.00₺", Fiyat = "69.99", Indirim = "%41", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-bisiklet-yaka-turuncu-tisort-bisiklet-yaka-tisort-hatem-sayki-44905-98-K.jpg", Baslik = "Bisiklet Yaka Turuncu Basic Tişört", Eskifiyat = "189.00₺", Fiyat = "129.90", Indirim = "%31", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };

                Urun urun6 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-mavi-tisort-8771-polo-tisort-html-45304-87-K.jpg", Baslik = "Desenli Mavi Polo Yaka Basic Tişört", Eskifiyat = "129.00₺", Fiyat = "49.99", Indirim = "%61", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun7 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-lacivert-tisort-8700-polo-tisort-hatem-sayki-45482-87-K.jpg", Baslik = "Desenli Lacivert Polo Yaka Tişört", Eskifiyat = "219.00₺", Fiyat = "49.99", Indirim = "%77", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun8 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-gri-tisort-8793-polo-tisort-html-41420-87-K.jpg", Baslik = "Desenli Gri Polo Yaka Tişört", Eskifiyat = "149.00₺", Fiyat = "69.99", Indirim = "%53", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun9 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-siyah-tisort-8794-polo-tisort-html-40453-87-K.jpg", Baslik = "Desenli Siyah Polo Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "69.99", Indirim = "%61", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun10 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-yesil-tisort-8622-polo-tisort-hatemoglu-45422-86-K.jpg", Baslik = "Desenli Yeşil Polo Yaka Tişört", Eskifiyat = "149.00₺", Fiyat = "39.99", Indirim = "%73", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };

                Urun urun11 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-lacivert-tisort-8526-hakim-yaka-tisort-html-43020-85-K.jpg", Baslik = "Koyu Lacivert Desenli Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun12 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-lacivert-tisort-8522-hakim-yaka-tisort-html-45462-85-K.jpg", Baslik = "Çizgili Lacivert Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun13 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-beyaz-tisort-8525-hakim-yaka-tisort-html-43027-85-K.jpg", Baslik = "Desenli Beyaz Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun14 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-lacivert-tisort-8520-hakim-yaka-tisort-html-46285-85-K.jpg", Baslik = "Desenli Kiremit Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun15 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-haki-tisort-8521-hakim-yaka-tisort-html-45466-85-K.jpg", Baslik = "Desenli Haki Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5, urun6, urun7, urun8, urun9, urun10, urun11, urun12, urun13, urun14, urun15 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Bisiklet Yaka Tişörtler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-baskili-regular-t-shirt-22512-online-ozel-hatemoglu-55095-22-K.jpg", Baslik = "Bisiklet Yaka Siyah Basic Tişört", Eskifiyat = "119.00₺", Fiyat = "69.99", Indirim = "%41", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-baskili-regular-t-shirt-22513-online-ozel-hatemoglu-55097-22-K.jpg", Baslik = "Bisiklet Yaka Lacivert Basic Tişört", Eskifiyat = "119.00₺", Fiyat = "69.99", Indirim = "%41", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/beyaz-baskili-regular-t-shirt-22511-online-ozel-hatemoglu-55093-22-K.jpg", Baslik = "Bisiklet Yaka Beyaz Basic Tişört", Eskifiyat = "119.00₺", Fiyat = "69.99", Indirim = "%41", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/haki-baskili-regular-t-shirt-online-ozel-hatemoglu-55099-22-K.jpg", Baslik = "Bisiklet Yaka Haki Basic Tişört", Eskifiyat = "119.00₺", Fiyat = "69.99", Indirim = "%41", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-bisiklet-yaka-turuncu-tisort-bisiklet-yaka-tisort-hatem-sayki-44905-98-K.jpg", Baslik = "Bisiklet Yaka Turuncu Basic Tişört", Eskifiyat = "189.00₺", Fiyat = "129.90", Indirim = "%31", Ozellikler = "Html Baskılı %100 Pamuk Regular T-shirt" };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Polo Tişörtler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-mavi-tisort-8771-polo-tisort-html-45304-87-K.jpg", Baslik = "Desenli Mavi Polo Yaka Basic Tişört", Eskifiyat = "129.00₺", Fiyat = "49.99", Indirim = "%61", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-lacivert-tisort-8700-polo-tisort-hatem-sayki-45482-87-K.jpg", Baslik = "Desenli Lacivert Polo Yaka Tişört", Eskifiyat = "219.00₺", Fiyat = "49.99", Indirim = "%77", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-gri-tisort-8793-polo-tisort-html-41420-87-K.jpg", Baslik = "Desenli Gri Polo Yaka Tişört", Eskifiyat = "149.00₺", Fiyat = "69.99", Indirim = "%53", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-siyah-tisort-8794-polo-tisort-html-40453-87-K.jpg", Baslik = "Desenli Siyah Polo Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "69.99", Indirim = "%61", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-polo-yaka-yesil-tisort-8622-polo-tisort-hatemoglu-45422-86-K.jpg", Baslik = "Desenli Yeşil Polo Yaka Tişört", Eskifiyat = "149.00₺", Fiyat = "39.99", Indirim = "%73", Ozellikler = "Karışım: %65 Polyester %35 Viskon\nYaka: Polo Yaka\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 96 cm,Bel: 82 cm\nGörseldeki Ürün Bedeni :  M" };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Hakim Yaka Tişörtler")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-lacivert-tisort-8526-hakim-yaka-tisort-html-43020-85-K.jpg", Baslik = "Koyu Lacivert Desenli Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-lacivert-tisort-8522-hakim-yaka-tisort-html-45462-85-K.jpg", Baslik = "Çizgili Lacivert Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-beyaz-tisort-8525-hakim-yaka-tisort-html-43027-85-K.jpg", Baslik = "Desenli Beyaz Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-lacivert-tisort-8520-hakim-yaka-tisort-html-46285-85-K.jpg", Baslik = "Desenli Kiremit Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-hakim-yaka-haki-tisort-8521-hakim-yaka-tisort-html-45466-85-K.jpg", Baslik = "Desenli Haki Hakim Yaka Tişört", Eskifiyat = "179.00₺", Fiyat = "49.99", Indirim = "%72", Ozellikler = "Karışım: %100 Pamuk\nYaka: Hakim Yaka\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 97 cm,Bel: 77 cm\nGörseldeki Ürün Bedeni :  M" };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun== "Kazaklar")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-tanimsiz-tanimsiz-triko-10711-bogazli-kazak-hatemoglu-53412-10-K.jpg", Baslik = "Yarım Balıkçı Siyah Kazak", Eskifiyat = "219.0₺", Fiyat = "149.90", Indirim = "%32", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nYarım Balıkçı Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/bej-balikci-yaka-kazak-20278-balikci-yaka-kazak-hatemoglu-54049-20-K.jpg", Baslik = "Balıkçı Yaka Bej Kazak", Eskifiyat = "199.90₺", Fiyat = "169.90", Indirim = "%15", Ozellikler = "Hatem Saykı Tanımsız %15 Yün %35 Akrilik %50 Polyester Tanımsız Triko" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/tas-tanimsiz-tanimsiz-triko-10713-bogazli-kazak-hatemoglu-53428-10-K.jpg", Baslik = "Yarım Balıkçı Bej Kazak", Eskifiyat = "219.00₺", Fiyat = "149.90", Indirim = "%32", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nYarım Balıkçı Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/balikci-yaka-antrasit-triko-bogazli-kazak-hatem-sayki-37888-82-K.jpg", Baslik = "Balıkçı Yaka Gri Yünlü Triko Kazak", Eskifiyat = "209.0₺", Fiyat = "59.90", Indirim = "%79", Ozellikler = "Kumaş: %50 Yün %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nPolo Yaka\nRenk bloklu\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/balikci-yaka-mor-triko-kazak-bogazli-kazak-html-46328-92-K.jpg", Baslik = "Balıkçı Yaka Mor Pamuklu Triko Kazak", Eskifiyat = "219.0₺", Fiyat = "129.90", Indirim = "%41", Ozellikler = "Kumaş: %50 Pamuk %50 AkrilikKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBalıkçı Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                Urun urun6 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-kirmizi-tanimsiz-tanimsiz-triko-20189-siyah-kazak-hatemoglu-54207-20-K.jpg", Baslik = "Desenli Kırmızı Bisiklet Yaka Siyah Kazak", Eskifiyat = "249.0₺", Fiyat = "169.90", Indirim = "%32", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun7 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-kgri-tanimsiz-tanimsiz-triko-lacivert-kazak-hatemoglu-54273-20-K.jpg", Baslik = "Desenli Gri Bisiklet Yaka Lacivert Kazak", Eskifiyat = "249.0₺", Fiyat = "169.90", Indirim = "%32", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun8 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/gri-tanimsiz-tanimsiz-triko-20172-gri-kazak-hatemoglu-54228-20-K.jpg", Baslik = "Desenli Taba Bisiklet Yaka Gri Kazak", Eskifiyat = "249.0₺", Fiyat = "159.90", Indirim = "%36", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun9 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-tanimsiz-tanimsiz-triko-20170-siyah-kazak-hatemoglu-54222-20-K.jpg", Baslik = "Desenli Gri Bisiklet Yaka Gri Kazak", Eskifiyat = "249.0₺", Fiyat = "159.90", Indirim = "%36", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun10 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-tanimsiz-tanimsiz-triko-20171-lacivert-kazak-hatemoglu-54225-20-K.jpg", Baslik = "Desenli Bordo Bisiklet Yaka Gri Kazak", Eskifiyat = "249.0₺", Fiyat = "159.90", Indirim = "%36", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                Urun urun11 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-tanimsiz-tanimsiz-triko-21911-lacivert-kazak-hatemoglu-54201-21-K.jpg", Baslik = "V Yaka Lacivert Triko Kazak", Eskifiyat = "249.00₺", Fiyat = "89.90", Indirim = "%64", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nV Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun12 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/gri-melanj-tanimsiz-tanimsiz-triko-gri-kazak-hatemoglu-54219-20-K.jpg", Baslik = "Zikzak Desenli Gri Bisiklet Yaka Kazak", Eskifiyat = "249.0₺", Fiyat = "149.9", Indirim = "%40", Ozellikler = "Hatem Saykı Tanımsız %50 Pamuk %50 Akrilik Tanımsız Triko" };
                Urun urun13 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-tanimsiz-tanimsiz-triko-20180-lacivert-kazak-hatemoglu-54216-20-K.jpg", Baslik = "Zikzak Desenli Lacivert Bisiklet Yaka Kazak", Eskifiyat = "249.0₺", Fiyat = "149.9", Indirim = "%40", Ozellikler = "Hatem Saykı Tanımsız %50 Pamuk %50 Akrilik Tanımsız Triko" };
                Urun urun14 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-tanimsiz-tanimsiz-triko-20179-siyah-kazak-hatemoglu-54213-20-K.jpg", Baslik = "Zikzak Desenli Siyah Bisiklet Yaka Kazak", Eskifiyat = "249.0₺", Fiyat = "149.9", Indirim = "%40", Ozellikler = "Hatem Saykı Tanımsız %50 Pamuk %50 Akrilik Tanımsız Triko" };
                Urun urun15 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-tanimsiz-tanimsiz-triko-21910-siyah-kazak-hatemoglu-54198-21-K.jpg", Baslik = "V Yaka Siyah Triko Kazak", Eskifiyat = "249.00₺", Fiyat = "89.90", Indirim = "%64", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nV Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                
                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5, urun6, urun7, urun8, urun9, urun10, urun11, urun12, urun13, urun14, urun15 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Boğazlı Kazaklar")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-tanimsiz-tanimsiz-triko-10711-bogazli-kazak-hatemoglu-53412-10-K.jpg", Baslik = "Yarım Balıkçı Siyah Kazak", Eskifiyat = "219.0₺", Fiyat = "149.90", Indirim = "%32", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nYarım Balıkçı Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/bej-balikci-yaka-kazak-20278-balikci-yaka-kazak-hatemoglu-54049-20-K.jpg", Baslik = "Balıkçı Yaka Bej Kazak", Eskifiyat = "199.90₺", Fiyat = "169.90", Indirim = "%15", Ozellikler = "Hatem Saykı Tanımsız %15 Yün %35 Akrilik %50 Polyester Tanımsız Triko" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/tas-tanimsiz-tanimsiz-triko-10713-bogazli-kazak-hatemoglu-53428-10-K.jpg", Baslik = "Yarım Balıkçı Bej Kazak", Eskifiyat = "219.00₺", Fiyat = "149.90", Indirim = "%32", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nYarım Balıkçı Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/balikci-yaka-antrasit-triko-bogazli-kazak-hatem-sayki-37888-82-K.jpg", Baslik = "Balıkçı Yaka Gri Yünlü Triko Kazak", Eskifiyat = "209.0₺", Fiyat = "59.90", Indirim = "%79", Ozellikler = "Kumaş: %50 Yün %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nPolo Yaka\nRenk bloklu\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/balikci-yaka-mor-triko-kazak-bogazli-kazak-html-46328-92-K.jpg", Baslik = "Balıkçı Yaka Mor Pamuklu Triko Kazak", Eskifiyat = "219.0₺", Fiyat = "129.90", Indirim = "%41", Ozellikler = "Kumaş: %50 Pamuk %50 AkrilikKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.85 cm, Göğüs: 96 cm, Bel: 75 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBalıkçı Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Bisiklet Yaka Kazaklar")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-kirmizi-tanimsiz-tanimsiz-triko-20189-siyah-kazak-hatemoglu-54207-20-K.jpg", Baslik = "Desenli Kırmızı Bisiklet Yaka Siyah Kazak", Eskifiyat = "249.0₺", Fiyat = "169.90", Indirim = "%32", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-kgri-tanimsiz-tanimsiz-triko-lacivert-kazak-hatemoglu-54273-20-K.jpg", Baslik = "Desenli Gri Bisiklet Yaka Lacivert Kazak", Eskifiyat = "249.0₺", Fiyat = "169.90", Indirim = "%32", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/gri-tanimsiz-tanimsiz-triko-20172-gri-kazak-hatemoglu-54228-20-K.jpg", Baslik = "Desenli Taba Bisiklet Yaka Gri Kazak", Eskifiyat = "249.0₺", Fiyat = "159.90", Indirim = "%36", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-tanimsiz-tanimsiz-triko-20170-siyah-kazak-hatemoglu-54222-20-K.jpg", Baslik = "Desenli Gri Bisiklet Yaka Gri Kazak", Eskifiyat = "249.0₺", Fiyat = "159.90", Indirim = "%36", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-tanimsiz-tanimsiz-triko-20171-lacivert-kazak-hatemoglu-54225-20-K.jpg", Baslik = "Desenli Bordo Bisiklet Yaka Gri Kazak", Eskifiyat = "249.0₺", Fiyat = "159.90", Indirim = "%36", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nBisiklet Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "V Yaka Kazaklar")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-tanimsiz-tanimsiz-triko-21911-lacivert-kazak-hatemoglu-54201-21-K.jpg", Baslik = "V Yaka Lacivert Triko Kazak", Eskifiyat = "249.00₺", Fiyat = "89.90", Indirim = "%64", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nV Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/gri-melanj-tanimsiz-tanimsiz-triko-gri-kazak-hatemoglu-54219-20-K.jpg", Baslik = "Zikzak Desenli Gri Bisiklet Yaka Kazak", Eskifiyat = "249.0₺", Fiyat = "149.9", Indirim = "%40", Ozellikler = "Hatem Saykı Tanımsız %50 Pamuk %50 Akrilik Tanımsız Triko" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-tanimsiz-tanimsiz-triko-20180-lacivert-kazak-hatemoglu-54216-20-K.jpg", Baslik = "Zikzak Desenli Lacivert Bisiklet Yaka Kazak", Eskifiyat = "249.0₺", Fiyat = "149.9", Indirim = "%40", Ozellikler = "Hatem Saykı Tanımsız %50 Pamuk %50 Akrilik Tanımsız Triko" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-tanimsiz-tanimsiz-triko-20179-siyah-kazak-hatemoglu-54213-20-K.jpg", Baslik = "Zikzak Desenli Siyah Bisiklet Yaka Kazak", Eskifiyat = "249.0₺", Fiyat = "149.9", Indirim = "%40", Ozellikler = "Hatem Saykı Tanımsız %50 Pamuk %50 Akrilik Tanımsız Triko" };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/siyah-tanimsiz-tanimsiz-triko-21910-siyah-kazak-hatemoglu-54198-21-K.jpg", Baslik = "V Yaka Siyah Triko Kazak", Eskifiyat = "249.00₺", Fiyat = "89.90", Indirim = "%64", Ozellikler = "Kumaş: %50 Pamuk %50 Akrilik\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.87 cm, Göğüs: 100 cm, Bel: 77 cm Kilo: 79kg\nGörseldeki Ürün Bedeni : M\nUzun Kol\nV Yaka\nDesenli\nYerli Üretim\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Pantolonlar")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-basic-slim-fit-pantolon-10504-kumas-pantolon-hatem-sayki-47896-10-K.jpg", Baslik = "Slim Fit Lacivert Kumaş Pantolon", Eskifiyat = "419.00₺", Fiyat = "269.90", Indirim = "%36", Ozellikler = "Kumaş: %41 Yün %54 Polyester %5 Elastan\nKalıp Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 42\nYandan Cep\nKlasik Kumaş Pantolon\nDüz Renk\nYerli Üretim\nNormal Bel\nYünlü Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/haki-forest-night-basic-slim-fit-pantolon-yeni-sezon-hatemoglu-53357-10-K.jpg", Baslik = "Slim Fit Haki Spor Pantolon", Eskifiyat = "419.00₺", Fiyat = "299.90", Indirim = "%28", Ozellikler = "Kumaş: %90 Pamuk %7 Polyester %3 Elastan\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\n5 Cep\nKanvas Pantolon\nDüz Renk\nYerli Üretim\nNormal Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/olive-basic-regular-pantolon-kanvas-pantolon-hatemoglu-48025-10-K.jpg", Baslik = "Slim Fit Bej Kanvas Pantolon", Eskifiyat = "219.00₺", Fiyat = "149.90", Indirim = "%32", Ozellikler = "Kumaş: %98 Pamuk %2 Elastan\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\nYandan Cep\nKanvas Pantolon\nDüz Renk\nYerli Üretim\nYüksek Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/akahverengi-k-kareli-slim-fit-pantolon-kumas-pantolon-hatem-sayki-47607-10-K.jpg", Baslik = "Slim Fit Kahverengi Kareli Kumaş Pantolon", Eskifiyat = "419.00₺", Fiyat = "299.90", Indirim = "%28", Ozellikler = "Kumaş: %100 Yün\nKalıp Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 42\nYandan Cep\nKlasik Kumaş Pantolon\nKareli\nYerli Üretim\nNormal Bel\n % 100 Yün Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-bej-pantolon7379-slim-fit-pantolon-hatem-sayki-39118-73-K.jpg", Baslik = "Slim Fit Bej Spor Pantolon", Eskifiyat = "419.00₺", Fiyat = "99.99", Indirim = "%76", Ozellikler = "Kumaş: %95 Pamuk %4 Polyester %1 Elastan\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\nYandan Cep\nKanvas Pantolon\nDüz Renk\nYerli Üretim\nNormal Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                Urun urun6 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-klasik-tas-pantolon-klasik-pantolon-hatemoglu-43599-70-K.jpg", Baslik = "Desenli Bej Klasik Pantolon", Eskifiyat = "249.00₺", Fiyat = "79.99", Indirim = "%68", Ozellikler = "HATEMOĞLU Desenli %57 Viskon %40 Polyester %3 Elastan Klasik Pantolon" };
                Urun urun7 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/dinamik-gri-pantolon7042-klasik-pantolon-hatemoglu-39935-70-K.jpg", Baslik = "Dinamik Gri Pantolon", Eskifiyat = "209.0₺", Fiyat = "129.90", Indirim = "%55", Ozellikler = "HATEMOĞLU Basic %62 Polyester %35 Viskon %3 Elastan Dinamik Pantolon" };
                Urun urun8 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-slim-fit-lacivert-pantolon7136-klasik-pantolon-hatem-sayki-39897-71-K.jpg", Baslik = "Desenli Slim Fit Lacivert Pantolon", Eskifiyat = "495.0₺", Fiyat = "149.90", Indirim = "%70", Ozellikler = "HATEM SAYKI Kazayağı %44 Yün %54 Polyester %2 Elastan Slim Fit Pantolon" };
                Urun urun9 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-d-desenli-regular-pantolon-7350-klasik-pantolon-hatemoglu-39178-73-K.jpg", Baslik = "Regular Lacivert Kanvas Pantolon", Eskifiyat = "209.00₺", Fiyat = "79.99", Indirim = "%72", Ozellikler = "HATEMOĞLU Desenli %48 Pamuk %48 Polyester %4 Elastan Regular Pantolon" };
                Urun urun10 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/regular-vizon-pantolon9061-klasik-pantolon-hatemoglu-39042-90-K.jpg", Baslik = "Regular Vizon Pantolon", Eskifiyat = "209.00₺", Fiyat = "99.99", Indirim = "%65", Ozellikler = "HATEMOĞLU Basic %97 PAMUK %3 ELASTAN Regular Pantolon" };

                Urun urun11 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-lacivert-yesil-pantolon6861-slim-fit-pantolon-hatem-sayki-40182-68-K.jpg", Baslik = "Slim Fit Lacivert Kot Pantolon", Eskifiyat = "419.00₺", Fiyat = "199.90", Indirim = "%52", Ozellikler = "HATEM SAYKI Pure Basic %87 Pamuk %11 Polyester %2 Elastan Slim Fit Pantolon" };
                Urun urun12 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/regular-lacivert-pantolon6825-regular-fit-pantolon-hatemoglu-43560-68-K.jpg", Baslik = "Regular Fit Lacivert Kot Pantolon", Eskifiyat = "419.90₺", Fiyat = "99.99", Indirim = "%76", Ozellikler = "Kumaş: %99 Pamuk %1 Elastan\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\n5 Cep\nJean Pantolon\nYerli Üretim\nYüksek Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun13 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-lacivert-pantolon6897-slim-fit-pantolon-html-39813-68-K.jpg", Baslik = "Slim Fit Lacivert Kot Pantolon", Eskifiyat = "419.90₺", Fiyat = "99.99", Indirim = "%76", Ozellikler = "HTML Basic %99 Pamuk %1 Elastan Slim Fit Pantolon" };
                Urun urun14 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/regular-siyah-pantolon-regular-fit-pantolon-hatem-sayki-43762-68-K.jpg", Baslik = "Regular Fit Siyah Kot Pantolon", Eskifiyat = "349.00₺", Fiyat = "229.90", Indirim = "%39", Ozellikler = "Kumaş: %98 Pamuk %2 Elastan\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\n5 Cep\nJean Pantolon\nYerli Üretim\nYüksek Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun15 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/regular-lacivert-pantolon6864-regular-fit-pantolon-hatem-sayki-40184-68-K.jpg", Baslik = "Regular Fit Lacivert Kot Pantolon", Eskifiyat = "419.00₺", Fiyat = "149.90", Indirim = "%64", Ozellikler = "HATEM SAYKI Basic %99 Pamuk %1 Elastan Regular Pantolon" };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5, urun6, urun7, urun8, urun9, urun10, urun11, urun12, urun13, urun14, urun15 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;

            }
            else if (g_urun == "Slim Fit Pantolonlar")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-basic-slim-fit-pantolon-10504-kumas-pantolon-hatem-sayki-47896-10-K.jpg", Baslik = "Slim Fit Lacivert Kumaş Pantolon", Eskifiyat = "419.00₺", Fiyat = "269.90", Indirim = "%36", Ozellikler = "Kumaş: %41 Yün %54 Polyester %5 Elastan\nKalıp Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 42\nYandan Cep\nKlasik Kumaş Pantolon\nDüz Renk\nYerli Üretim\nNormal Bel\nYünlü Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/haki-forest-night-basic-slim-fit-pantolon-yeni-sezon-hatemoglu-53357-10-K.jpg", Baslik = "Slim Fit Haki Spor Pantolon", Eskifiyat = "419.00₺", Fiyat = "299.90", Indirim = "%28", Ozellikler = "Kumaş: %90 Pamuk %7 Polyester %3 Elastan\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\n5 Cep\nKanvas Pantolon\nDüz Renk\nYerli Üretim\nNormal Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/olive-basic-regular-pantolon-kanvas-pantolon-hatemoglu-48025-10-K.jpg", Baslik = "Slim Fit Bej Kanvas Pantolon", Eskifiyat = "219.00₺", Fiyat = "149.90", Indirim = "%32", Ozellikler = "Kumaş: %98 Pamuk %2 Elastan\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\nYandan Cep\nKanvas Pantolon\nDüz Renk\nYerli Üretim\nYüksek Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/akahverengi-k-kareli-slim-fit-pantolon-kumas-pantolon-hatem-sayki-47607-10-K.jpg", Baslik = "Slim Fit Kahverengi Kareli Kumaş Pantolon", Eskifiyat = "419.00₺", Fiyat = "299.90", Indirim = "%28", Ozellikler = "Kumaş: %100 Yün\nKalıp Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 42\nYandan Cep\nKlasik Kumaş Pantolon\nKareli\nYerli Üretim\nNormal Bel\n % 100 Yün Kumaş\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-bej-pantolon7379-slim-fit-pantolon-hatem-sayki-39118-73-K.jpg", Baslik = "Slim Fit Bej Spor Pantolon", Eskifiyat = "419.00₺", Fiyat = "99.99", Indirim = "%76", Ozellikler = "Kumaş: %95 Pamuk %4 Polyester %1 Elastan\nKalıp: Slim Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\nYandan Cep\nKanvas Pantolon\nDüz Renk\nYerli Üretim\nNormal Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Klasik Pantolonlar")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-klasik-tas-pantolon-klasik-pantolon-hatemoglu-43599-70-K.jpg", Baslik = "Desenli Bej Klasik Pantolon", Eskifiyat = "249.00₺", Fiyat = "79.99", Indirim = "%68", Ozellikler = "HATEMOĞLU Desenli %57 Viskon %40 Polyester %3 Elastan Klasik Pantolon" };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/dinamik-gri-pantolon7042-klasik-pantolon-hatemoglu-39935-70-K.jpg", Baslik = "Dinamik Gri Pantolon", Eskifiyat = "209.0₺", Fiyat = "129.90", Indirim = "%55", Ozellikler = "HATEMOĞLU Basic %62 Polyester %35 Viskon %3 Elastan Dinamik Pantolon" };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/desenli-slim-fit-lacivert-pantolon7136-klasik-pantolon-hatem-sayki-39897-71-K.jpg", Baslik = "Desenli Slim Fit Lacivert Pantolon", Eskifiyat = "495.0₺", Fiyat = "149.90", Indirim = "%70", Ozellikler = "HATEM SAYKI Kazayağı %44 Yün %54 Polyester %2 Elastan Slim Fit Pantolon" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/lacivert-d-desenli-regular-pantolon-7350-klasik-pantolon-hatemoglu-39178-73-K.jpg", Baslik = "Regular Lacivert Kanvas Pantolon", Eskifiyat = "209.00₺", Fiyat = "79.99", Indirim = "%72", Ozellikler = "HATEMOĞLU Desenli %48 Pamuk %48 Polyester %4 Elastan Regular Pantolon" };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/regular-vizon-pantolon9061-klasik-pantolon-hatemoglu-39042-90-K.jpg", Baslik = "Regular Vizon Pantolon", Eskifiyat = "209.00₺", Fiyat = "99.99", Indirim = "%65", Ozellikler = "HATEMOĞLU Basic %97 PAMUK %3 ELASTAN Regular Pantolon" };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
            else if (g_urun == "Kot Pantolonlar")
            {
                Urun urun1 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-lacivert-yesil-pantolon6861-slim-fit-pantolon-hatem-sayki-40182-68-K.jpg", Baslik = "Slim Fit Lacivert Kot Pantolon", Eskifiyat = "419.00₺", Fiyat = "199.90", Indirim = "%52", Ozellikler = "HATEM SAYKI Pure Basic %87 Pamuk %11 Polyester %2 Elastan Slim Fit Pantolon" };
                Urun urun2 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/regular-lacivert-pantolon6825-regular-fit-pantolon-hatemoglu-43560-68-K.jpg", Baslik = "Regular Fit Lacivert Kot Pantolon", Eskifiyat = "419.90₺", Fiyat = "99.99", Indirim = "%76", Ozellikler = "Kumaş: %99 Pamuk %1 Elastan\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\n5 Cep\nJean Pantolon\nYerli Üretim\nYüksek Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun3 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/slim-fit-lacivert-pantolon6897-slim-fit-pantolon-html-39813-68-K.jpg", Baslik = "Slim Fit Lacivert Kot Pantolon", Eskifiyat = "419.90₺", Fiyat = "99.99", Indirim = "%76", Ozellikler = "HTML Basic %99 Pamuk %1 Elastan Slim Fit Pantolon" };
                Urun urun4 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/regular-siyah-pantolon-regular-fit-pantolon-hatem-sayki-43762-68-K.jpg", Baslik = "Regular Fit Siyah Kot Pantolon", Eskifiyat = "349.00₺", Fiyat = "229.90", Indirim = "%39", Ozellikler = "Kumaş: %98 Pamuk %2 Elastan\nKalıp: Regular Fit\nModel Ölçüsü : Boy: 1.88 cm, Göğüs: 106 cm, Bel: 85 cm Kilo: 80kg\nGörseldeki Ürün Bedeni : 31\n5 Cep\nJean Pantolon\nYerli Üretim\nYüksek Bel\nStüdyo çekim ortamında bulunan ışık ve gölgelenmelerden dolayı görsellerde renk farklılıkları olabilir." };
                Urun urun5 = new Urun { Tur = g_urun, Resim = "https://www.hatemoglu.com/regular-lacivert-pantolon6864-regular-fit-pantolon-hatem-sayki-40184-68-K.jpg", Baslik = "Regular Fit Lacivert Kot Pantolon", Eskifiyat = "419.00₺", Fiyat = "149.90", Indirim = "%64", Ozellikler = "HATEM SAYKI Basic %99 Pamuk %1 Elastan Regular Pantolon" };

                List<Urun> UrunlerList = new List<Urun> { urun1, urun2, urun3, urun4, urun5 };
                StaticList = UrunlerList;
                liste.ItemsSource = UrunlerList;
            }
        }

        private async void liste_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {        
            var seciliBaslik = (e.CurrentSelection.FirstOrDefault() as Urun)?.Baslik;
            var seciliFiyat = (e.CurrentSelection.FirstOrDefault() as Urun)?.Fiyat;
            var seciliEskiFiyat = (e.CurrentSelection.FirstOrDefault() as Urun)?.Eskifiyat;
            var seciliIndirim = (e.CurrentSelection.FirstOrDefault() as Urun)?.Indirim;
            var seciliResim = (e.CurrentSelection.FirstOrDefault() as Urun)?.Resim;
            var seciliOzellik = (e.CurrentSelection.FirstOrDefault() as Urun)?.Ozellikler;
            var secilitur = (e.CurrentSelection.FirstOrDefault() as Urun)?.Tur;

            await Navigation.PushAsync(new UrunDetay(secilitur,seciliBaslik,seciliFiyat,seciliEskiFiyat,seciliIndirim,seciliResim,seciliOzellik));
        }

        [Obsolete]
        public async void filtrele_Clicked(object sender, EventArgs e)
        {
            await PopupNavigation.PushAsync(new FiltrelePopup(StaticList));
        }

        private void sıfırla_Clicked(object sender, EventArgs e)
        {
            liste.ItemsSource = StaticList;
        }
    }
}